// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvkizjwyajwqyzpnyrjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2a2l6and5YWp3cXl6cG55cmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTA2MTksImV4cCI6MjA3MDQyNjYxOX0.aezAqiZ1P8Rgk2HlFKc-bwxKMYHeerbxzteEwSYxg9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});